spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost/springboot?characterEncoding=utf-8&useSSL=false
  #开发状态下sql语句是打印显示的
  jpa:
    show-sql: true
server:
  context-path: /demo
#logging:
#  pattern:
 #   console: '%d - %msg%n'
 # path:
 # file:log/base.log
 # level: debug